# Generated by Django 3.2.3 on 2024-04-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subordinate',
            name='kingdom',
            field=models.CharField(max_length=128),
        ),
    ]
