# Generated by Django 3.2.3 on 2024-04-10 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_subordinate_kingdom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subordinate',
            name='kingdom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kingdom'),
        ),
    ]
