# Generated by Django 3.2.3 on 2024-04-16 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_subordinate_kingdom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=20)),
                ('correct_answer', models.CharField(max_length=8)),
                ('kingdom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kingdom')),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
