# Generated by Django 3.2.3 on 2024-04-17 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_question_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField()),
                ('king', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.king')),
                ('subordinate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subordinate')),
            ],
        ),
    ]
